### ISSUE TITLE
一个开始

### ISSUE THREAD

**Issue by kocomic** [kocomic/kc-comments#10]
https://chocmax.com/2018/07/05/yi-ge-kai-shi/

**Comment by L-Jovi** [comment]
## 测试 markdown

> 引用测试

```
const foo = 'bar'
```

## 表格

| foo | bar |
| - | - |
| xxx | mmm |

__帅气__

**Comment by kocomic** [comment]
> @L-Jovi
> ## 测试 markdown
> 
> > 引用测试
> 
> ```
> const foo = 'bar'
> ```
> 
> ## 表格
> 
> | foo | bar |
> | - | - |
> | xxx | mmm |
> 
> __帅气__
> 
> 

帅气！

**Comment by kocomic** [comment]
奥术大师
